FROM 127.0.0.1:5000/dev-base:1.0.4 AS project

ENV DEBIAN_FRONTEND=noninteractive

USER root

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    podman \
    && rm -rf /var/lib/apt/lists/*

USER developer