ARG REGISTRY_ADDRESS=127.0.0.1:5000
ARG DEV_BASE_TAG=latest
FROM ${REGISTRY_ADDRESS}/dev-base:${DEV_BASE_TAG} AS base

ARG USERNAME=developer
ARG USER_UID=1000
ARG USER_GID=1000

FROM base AS monolith-dev

USER root

ENV GOBIN=/usr/local/bin
ENV GOTOOLCHAIN=local
ENV DOTNET_ROOT=/usr/share/dotnet
ENV DOTNET_CLI_TELEMETRY_OPTOUT=1
ENV DOTNET_NOLOGO=1
ENV DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
ENV NUGET_CLI_TELEMETRY_OPTOUT=1
ENV PNPM_HOME=/home/${USERNAME}/.local/share/pnpm
ENV PATH=/usr/local/node/bin:${PNPM_HOME}:/usr/local/go/bin:${DOTNET_ROOT}:${DOTNET_ROOT}/tools:${PATH}

COPY scripts/toolchains/install-nodejs.sh /tmp/install-nodejs.sh
COPY scripts/toolchains/install-typescript.sh /tmp/install-typescript.sh
COPY scripts/toolchains/install-python.sh /tmp/install-python.sh
COPY scripts/toolchains/install-golang.sh /tmp/install-golang.sh
COPY scripts/toolchains/install-dotnet.sh /tmp/install-dotnet.sh

RUN chmod +x /tmp/install-nodejs.sh /tmp/install-typescript.sh /tmp/install-python.sh /tmp/install-golang.sh /tmp/install-dotnet.sh \
    && /tmp/install-nodejs.sh \
    && /tmp/install-typescript.sh \
    && /tmp/install-python.sh \
    && /tmp/install-golang.sh \
    && /tmp/install-dotnet.sh \
    && rm -f /tmp/install-nodejs.sh /tmp/install-typescript.sh /tmp/install-python.sh /tmp/install-golang.sh /tmp/install-dotnet.sh

FROM monolith-dev AS project

USER ${USERNAME}