ARG REGISTRY_ADDRESS=127.0.0.1:5000
ARG DEV_BASE_TAG=latest
FROM ${REGISTRY_ADDRESS}/dev-base:${DEV_BASE_TAG} AS base

ARG USERNAME=developer
ARG USER_UID=1000
ARG USER_GID=1000

FROM base AS dotnet-dev

USER root

ENV DOTNET_ROOT=/usr/share/dotnet
ENV PATH=${PATH}:${DOTNET_ROOT}:${DOTNET_ROOT}/tools
ENV DOTNET_CLI_TELEMETRY_OPTOUT=1
ENV DOTNET_NOLOGO=1
ENV DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
ENV NUGET_CLI_TELEMETRY_OPTOUT=1
ENV POWERSHELL_TELEMETRY_OPTOUT=1

COPY scripts/toolchains/install-dotnet.sh /tmp/install-dotnet.sh

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    python3 \
    python3-pip \
    python3-venv \
    pipx \
    && rm -rf /var/lib/apt/lists/*

RUN PIPX_BIN_DIR=/usr/local/bin PIPX_HOME=/opt/pipx pipx install azure-cli \
    && install -d -m 0755 -o ${USER_UID} -g ${USER_GID} /home/${USERNAME}/.azure \
    && HOME=/home/${USERNAME} /usr/local/bin/az extension add --name azure-devops \
    && HOME=/home/${USERNAME} /usr/local/bin/az extension add --name application-insights \
    && chown -R ${USER_UID}:${USER_GID} /home/${USERNAME}/.azure

RUN python3 -m pip install --no-cache-dir --break-system-packages \
    Pillow \
    pytesseract

RUN curl -fsSL https://aka.ms/install-artifacts-credprovider.sh -o /tmp/install-artifacts-credprovider.sh \
    && chmod +x /tmp/install-dotnet.sh /tmp/install-artifacts-credprovider.sh \
    && /tmp/install-dotnet.sh \
    && install -d -m 0755 /home/${USERNAME}/.local/share/MicrosoftCredentialProvider \
    && install -d -m 0755 /home/${USERNAME}/.local/.IdentityService \
    && install -d -m 0755 /home/${USERNAME}/.nuget/share \
    && HOME=/home/${USERNAME} /tmp/install-artifacts-credprovider.sh \
    && chown -R ${USERNAME}:${USERNAME} /home/${USERNAME}/.local \
    && chown -R ${USERNAME}:${USERNAME} /home/${USERNAME}/.nuget \
    && chown -R ${USERNAME}:${USERNAME} /home/${USERNAME}/.microsoft \
    && rm -f /tmp/install-dotnet.sh /tmp/install-artifacts-credprovider.sh

FROM dotnet-dev AS project

USER ${USERNAME}
