ARG REGISTRY_ADDRESS=127.0.0.1:5000
ARG DEV_BASE_TAG=latest
FROM ${REGISTRY_ADDRESS}/dev-base:${DEV_BASE_TAG} AS base

ARG USERNAME=developer
ARG USER_UID=1000
ARG USER_GID=1000

FROM base AS nodejs-dev

USER root

ENV PNPM_HOME=/home/${USERNAME}/.local/share/pnpm
ENV PATH=/usr/local/node/bin:${PNPM_HOME}:${PATH}

COPY scripts/toolchains/install-nodejs.sh /tmp/install-nodejs.sh

RUN chmod +x /tmp/install-nodejs.sh \
    && /tmp/install-nodejs.sh \
    && rm -f /tmp/install-nodejs.sh

FROM nodejs-dev AS project

USER ${USERNAME}