ARG REGISTRY_ADDRESS=127.0.0.1:5000
ARG DEV_BASE_TAG=latest
FROM ${REGISTRY_ADDRESS}/dev-base:${DEV_BASE_TAG} AS base

ARG USERNAME=developer
ARG USER_UID=1000
ARG USER_GID=1000

FROM base AS python-dev

USER root

COPY scripts/toolchains/install-python.sh /tmp/install-python.sh

RUN chmod +x /tmp/install-python.sh \
    && /tmp/install-python.sh \
    && rm -f /tmp/install-python.sh

FROM python-dev AS project

USER ${USERNAME}
