ARG REGISTRY_ADDRESS=127.0.0.1:5000
ARG DEV_BASE_TAG=latest
FROM ${REGISTRY_ADDRESS}/dev-base:${DEV_BASE_TAG} AS base

ARG USERNAME=developer
ARG USER_UID=1000
ARG USER_GID=1000

FROM base AS python-dev

USER root

# Python
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    python3 \
    python3-pip \
    python3-venv \
    pipx \
    && rm -rf /var/lib/apt/lists/*

RUN python3 -m pip install --no-cache-dir --break-system-packages \
    black \
    debugpy

# OCR
RUN python3 -m pip install --no-cache-dir --break-system-packages \
    Pillow \
    pytesseract \
    pytest \
    ruff

FROM python-dev AS project

USER ${USERNAME}
