ARG REGISTRY_ADDRESS=127.0.0.1:5000
ARG NODEJS_DEV_TAG=latest
FROM ${REGISTRY_ADDRESS}/nodejs-dev:${NODEJS_DEV_TAG} AS base

ARG USERNAME=developer
ARG USER_UID=1000
ARG USER_GID=1000

FROM base AS typescript-dev

USER root

COPY scripts/toolchains/install-typescript.sh /tmp/install-typescript.sh

RUN chmod +x /tmp/install-typescript.sh \
    && /tmp/install-typescript.sh \
    && rm -f /tmp/install-typescript.sh

FROM typescript-dev AS project

USER ${USERNAME}