ARG REGISTRY_ADDRESS=127.0.0.1:5000
ARG DEV_BASE_TAG=latest
FROM ${REGISTRY_ADDRESS}/dev-base:${DEV_BASE_TAG} AS base

ARG USERNAME=developer
ARG USER_UID=1000
ARG USER_GID=1000

FROM base AS golang-dev

USER root

ENV GOBIN=/usr/local/bin
ENV GOTOOLCHAIN=local
ENV PATH=/usr/local/go/bin:${PATH}
COPY scripts/toolchains/install-golang.sh /tmp/install-golang.sh

RUN chmod +x /tmp/install-golang.sh \
    && /tmp/install-golang.sh \
    && rm -f /tmp/install-golang.sh

FROM golang-dev AS project

USER ${USERNAME}
